# Generated by Django 5.0.3 on 2024-03-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_articlescope'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescope',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
